#!/bin/bash

if (( $# != 2 )); then
	echo "nombre d'argument incorrect"
	exit 1
elif [[ $1 != +([0-9]) || $2 != +([0-9]) ]]; then
	echo "argument incorrect"
        exit 1
else
	somme=$(($1 + $2))
	echo "$1 + $2 = $somme"
fi
