#!/bin/bash

if (( $# != 3 )); then
        echo "nombre d'argument incorrect"
        exit 1
elif [[ $1 != +([0-9]) || $2 != +([0-9]) || $3 != +([0-9]) ]]; then
        echo "argument incorrect"
        exit 1
else
        if [[ $1 > $2 && $1 > $3 ]]; then
        	echo "$1 est le plus grand"
	elif [[ $2 > $1 && $2 > $3 ]]; then
                echo "$2 est le plus grand"
	elif [[ $3 > $1 && $3 > $2 ]]; then
                echo "$3 est le plus grand"
	else
                echo "il n'y a pas d'argument plus grand que les autres"
	fi
fi


